#ifndef RESOURCEDEF_H
#define RESOURCEDEF_H

#define RES_EMPTY ""
#define RES_ON ":/ui_ctrls/UICtrls/Res/poweron.bmp"
#define RES_OFF ":/ui_ctrls/UICtrls/Res/poweroff.bmp"

#define RES_VALVE_GAS ":/ui_ctrls/UICtrls/Res/valve-gas.png"
#define RES_SVALVE_1  ":/ui_ctrls/Res/svalve1.png"
#define RES_SVALVE_2  ":/ui_ctrls/Res/svalve2.png"
#define RES_SVALVE_3  ":/ui_ctrls/Res/svalve3.png"
#define RES_SVALVE_4  ":/ui_ctrls/Res/svalve4.png"
#define RES_SVALVE_5  ":/ui_ctrls/Res/svalve5.png"
#define RES_SVALVE_6  ":/ui_ctrls/Res/svalve6.png"
#define RES_SVALVE_7  ":/ui_ctrls/Res/svalve7.png"
#define RES_SVALVE_8  ":/ui_ctrls/Res/svalve8.png"
#define RES_MFC ":/ui_ctrls/UICtrls/Res/mfc.png"
#define RES_PFC ":/ui_ctrls/UICtrls/Res/pfc.png"
#define RES_VALVE_GAS_LEFT ":/ui_ctrls/UICtrls/Res/valve-gas-left.png"
#define RES_TC ":/ui_ctrls/UICtrls/Res/temperature_controller.png"
#define RES_CYLINDER_UP ":/ui_ctrls/UICtrls/Res/cylinder_up.png"
#define RES_CYLINDER_DOWN ":/ui_ctrls/UICtrls/Res/cylinder_down.png"
#define RES_GC ":/ui_ctrls/UICtrls/Res/gc.png"
#define RES_MECHANICAL_PUMP ":/ui_ctrls/UICtrls/Res/mechanical_pump.png"
#define RES_WATER_PUMP ":/ui_ctrls/UICtrls/Res/water_pump.png"
#define RES_VALVE_ELECTRIC ":/ui_ctrls/UICtrls/Res/valve_electric.png"
#define RES_ELECTRIC_CYLINDER ":/ui_ctrls/UICtrls/Res/electric_cylinder.png"
#define RES_ALARM ":/ui_ctrls/UICtrls/Res/alarm.png"
#define RES_SRV_ON ":/ui_ctrls/UICtrls/Res/srv_on.png"
#define RES_MOTOR ":/ui_ctrls/UICtrls/Res/motor.png"
#define RES_JIEJIN_ON ":/ui_ctrls/UICtrls/Res/jiejin_on.png"

#define ICON_CONTROL ":/ui_ctrls/Res/icon_control.png"
#define ICON_WORKFLOW ":/ui_ctrls/Res/icon_workflow.png"
#define ICON_MOTOR ":/ui_ctrls/Res/icon_motor.png"
#define ICON_DISTRIBUTOR ":/ui_ctrls/Res/icon_distributor.png"
#define ICON_TREND ":/ui_ctrls/Res/icon_trend.png"
#define ICON_HISTORY ":/ui_ctrls/Res/icon_history.png"

#endif // RESOURCEDEF_H
