#!/usr/bin/env python

"""
Common definitions for the module sharing.
"""

__author__ = 'Yun Hua'
__email__ = 'huayunflys@126.com'
__url__ = 'https://github.com/huayunfly/goiot'
__license__ = 'Apache License, Version 2.0'
__version__ = '0.1'
__status__ = 'Beta'


class FlowVar(object):
    """
    Variable definition for the batch data flowing in the device or service.
    """
    def __init__(self, names, indexes,
                 values, op_mode, op_results, trans_id):
        """
        Initialize the variable object.
        Args:
            names: Variable name list can be empty if the index is presented.
            indexes: Variable index list in the parent device or service,
                        which can be tag_id or device inner index.
            values: Variable value list.
            op_mode: Operation mode.
            op_results: Operation result list.
            trans_id: Transaction id generated by the device client.
        """
        self.names = names
        self.indexes = indexes
        self.values = values
        self.op_mode = op_mode
        self.op_results = op_results
        self.trans_id = trans_id
